// Mocks generated by Mockito 5.4.6 from annotations
// in mozzy/test/mozzy_ii/domains/feedback/feedback_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mozzy/mozzy_ii/domains/feedback/models/feedback_model.dart'
    as _i4;
import 'package:mozzy/mozzy_ii/domains/feedback/services/feedback_service.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FeedbackService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedbackService extends _i1.Mock implements _i2.FeedbackService {
  MockFeedbackService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> submitFeedback({
    required _i4.FeedbackType? type,
    required String? message,
    _i4.FeedbackContactPreference? contactPreference =
        _i4.FeedbackContactPreference.none,
    String? contactValue,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitFeedback, [], {
              #type: type,
              #message: message,
              #contactPreference: contactPreference,
              #contactValue: contactValue,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.FeedbackModel>> watchOpenFeedback() =>
      (super.noSuchMethod(
            Invocation.method(#watchOpenFeedback, []),
            returnValue: _i3.Stream<List<_i4.FeedbackModel>>.empty(),
          )
          as _i3.Stream<List<_i4.FeedbackModel>>);

  @override
  _i3.Future<void> updateFeedbackStatus({
    required String? feedbackId,
    required _i4.FeedbackStatus? status,
    String? adminNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateFeedbackStatus, [], {
              #feedbackId: feedbackId,
              #status: status,
              #adminNote: adminNote,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
