// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUO3vA0GSHviCcJu4ECX9nQPI_iKKe0_s',
    appId: '1:149673701591:web:2051eda0b2fa5ccd348092',
    messagingSenderId: '149673701591',
    projectId: 'mozzy-v2',
    authDomain: 'mozzy-v2.firebaseapp.com',
    storageBucket: 'mozzy-v2.firebasestorage.app',
    measurementId: 'G-P3DYC8LWZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkAEilz69Y1LXSGE5lHYWVsxpWDYxn50c',
    appId: '1:149673701591:android:8b8bb2701daf0720348092',
    messagingSenderId: '149673701591',
    projectId: 'mozzy-v2',
    storageBucket: 'mozzy-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDU3slAnweGlzok4vvoYThVl3OzAClh9g',
    appId: '1:149673701591:ios:3c75a20b18497d38348092',
    messagingSenderId: '149673701591',
    projectId: 'mozzy-v2',
    storageBucket: 'mozzy-v2.firebasestorage.app',
    iosClientId:
        '149673701591-9ugvl6hcrtrp0qkagcsie6gbjnqhoina.apps.googleusercontent.com',
    iosBundleId: 'package com.humantric.mozzy2',
  );
}
