import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import '../../../core/config/integration_test_config.dart';
import '../repositories/job_repository.dart';
import '../repositories/firestore_job_repository.dart';
import '../models/job_post_model.dart';
import '../providers/jobs_location_provider.dart';
import '../../../app/auth/auth_service.dart';
import '../../../geo/models/location_parts.dart';
import '../../chat/providers/chat_provider.dart';

part 'job_provider.g.dart';
part 'job_provider.freezed.dart';

final jobRepositoryProvider = Provider<JobRepository>((ref) {
  return FirestoreJobRepository(FirebaseFirestore.instance);
});

final currentJobsUserIdProvider = Provider<String?>((ref) {
  if (IntegrationTestConfig.enabled) {
    return IntegrationTestConfig.testUserId;
  }
  return ref.watch(authStateProvider).value?.uid;
});

@riverpod
class JobFilters extends _$JobFilters {
  @override
  JobFiltersState build() => const JobFiltersState();

  void setCategory(String? category) => state = state.copyWith(category: category);
  void setJobType(JobType? jobType) => state = state.copyWith(jobType: jobType);
  void setSearch(String? search) => state = state.copyWith(search: search);
}

@freezed
abstract class JobFiltersState with _$JobFiltersState {
  const factory JobFiltersState({
    String? category,
    JobType? jobType,
    String? search,
  }) = _JobFiltersState;
}


final nearbyJobsProvider = StreamProvider.family.autoDispose<List<JobPostModel>, String>((ref, kecamatan) {
  final filters = ref.watch(jobFiltersProvider);
  final repo = ref.watch(jobRepositoryProvider);
  return repo.watchNearbyJobs(
    kecamatan: kecamatan,
    category: filters.category,
    jobType: filters.jobType,
  ).map((jobs) {
    // Client-side sorting for Boosted jobs (MVP)
    final sortedJobs = List<JobPostModel>.from(jobs);
    sortedJobs.sort((a, b) {
      // 1. Boosted status (active boost first)
      if (a.isBoostActive && !b.isBoostActive) return -1;
      if (!a.isBoostActive && b.isBoostActive) return 1;
      
      // 2. Signal Score (if both or neither are boosted)
      if (a.signalScore != b.signalScore) {
        return b.signalScore.compareTo(a.signalScore);
      }
      
      // 3. Recency
      return b.createdAt.compareTo(a.createdAt);
    });
    return sortedJobs;
  });
});

final jobDetailProvider = FutureProvider.family.autoDispose<JobPostModel?, String>((ref, jobId) {
  final repo = ref.watch(jobRepositoryProvider);
  return repo.fetchJobById(jobId);
});

final jobDetailStreamProvider = StreamProvider.family.autoDispose<JobPostModel?, String>((ref, jobId) {
  final repo = ref.watch(jobRepositoryProvider);
  return repo.watchJobById(jobId);
});

@riverpod
Stream<List<JobPostModel>> ownerJobs(Ref ref, {required String ownerId, JobPostStatus? status}) {
  final repo = ref.watch(jobRepositoryProvider);
  return repo.watchOwnerJobs(ownerId, status: status);
}

@riverpod
class MyJobsFilter extends _$MyJobsFilter {
  @override
  JobPostStatus? build() => null; // null means all

  void setStatus(JobPostStatus? status) => state = status;
}

@riverpod
Stream<List<JobPostModel>> myJobs(Ref ref) {
  final user = ref.watch(authStateProvider).value;
  if (user == null) return Stream.value([]);
  
  final status = ref.watch(myJobsFilterProvider);
  final repo = ref.watch(jobRepositoryProvider);
  return repo.watchOwnerJobs(user.uid, status: status);
}

@riverpod
class JobActionController extends _$JobActionController {
  @override
  AsyncValue<void> build() => const AsyncValue.data(null);

  Future<void> createJob({
    required String title,
    required String companyName,
    required String description,
    required String category,
    required JobType jobType,
    required WorkType workType,
    required SalaryType salaryType,
    required int salaryMin,
    required int salaryMax,
  }) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      final repo = ref.read(jobRepositoryProvider);
      final user = ref.read(authStateProvider).value;
      if (user == null) throw Exception('jobs.loginRequired');
      final userId = user.uid;

      final LocationParts location = await ref.read(effectiveJobsLocationProvider.future);
      
      // Basic validation
      if (salaryType != SalaryType.negotiable) {
        if (salaryMin <= 0 || salaryMax <= 0) throw Exception('jobs.invalidSalaryRange');
        if (salaryMin > salaryMax) throw Exception('jobs.invalidSalaryRange');
      }

      final job = JobPostModel(
        id: '', // Generated by Firestore
        title: title,
        description: description,
        companyName: companyName,
        ownerId: userId,
        ownerName: user.displayName ?? 'User $userId',
        ownerPhotoUrl: user.photoURL,
        category: category,
        jobType: jobType,
        workType: workType,
        salaryType: salaryType,
        salaryMin: salaryMin,
        salaryMax: salaryMax,
        locationParts: location,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
        expiresAt: DateTime.now().add(const Duration(days: 30)),
        status: 'open',
      );

      await repo.createJob(job);
      
      // Invalidate providers to refresh list
      ref.invalidate(nearbyJobsProvider);
      return;
    });
  }

  Future<void> archiveJob(String jobId) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      await ref.read(jobRepositoryProvider).archiveJob(jobId);
      ref.invalidate(jobDetailProvider(jobId));
      ref.invalidate(nearbyJobsProvider);
      ref.invalidate(myJobsProvider);
    });
  }

  Future<void> closeJob(String jobId) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      await ref.read(jobRepositoryProvider).closeJob(jobId);
      ref.invalidate(jobDetailProvider(jobId));
      ref.invalidate(nearbyJobsProvider);
      ref.invalidate(myJobsProvider);
    });
  }

  Future<void> restoreJob(String jobId) async {
    state = const AsyncValue.loading();
    state = await AsyncValue.guard(() async {
      await ref.read(jobRepositoryProvider).restoreJob(jobId);
      ref.invalidate(jobDetailProvider(jobId));
      ref.invalidate(nearbyJobsProvider);
      ref.invalidate(myJobsProvider);
    });
  }

  Future<String?> applyJob(JobPostModel job) async {
    state = const AsyncValue.loading();
    String? roomId;
    state = await AsyncValue.guard(() async {
      final user = ref.read(authStateProvider).value;
      if (user == null) throw Exception('jobs.loginRequired');
      if (user.uid == job.ownerId) throw Exception('jobs.ownerCannotApply');

      final chatRepo = ref.read(chatRepositoryProvider);
      final result = await chatRepo.getOrCreateJobChatRoom(
        applicantId: user.uid,
        ownerId: job.ownerId,
        jobId: job.id,
        jobTitle: job.title,
      );

      roomId = result.room.id;
      final wasCreated = result.wasCreated;

      if (wasCreated) {
        await ref.read(jobRepositoryProvider).incrementChatCount(job.id);
      }

      await ref.read(jobRepositoryProvider).ensureApplicantRecord(
        job: job,
        applicantId: user.uid,
        applicantName: user.displayName ?? 'User ${user.uid}',
        applicantPhotoUrl: user.photoURL,
        chatRoomId: roomId!,
      );
    });
    return roomId;
  }
}
