// Mocks generated by Mockito 5.4.6 from annotations
// in mozzy/test/mozzy_ii/domains/feed/semantic_ranking_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:mozzy/mozzy_ii/domains/feed/models/feed_item_model.dart' as _i5;
import 'package:mozzy/mozzy_ii/domains/feed/models/user_feed_context.dart'
    as _i6;
import 'package:mozzy/mozzy_ii/domains/feed/services/feed_ranking_service.dart'
    as _i2;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i3;
import 'package:state_notifier/state_notifier.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [FeedRankingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedRankingService extends _i1.Mock
    implements _i2.FeedRankingService {
  MockFeedRankingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Ref get ref =>
      (super.noSuchMethod(
            Invocation.getter(#ref),
            returnValue: _i4.dummyValue<_i3.Ref>(this, Invocation.getter(#ref)),
          )
          as _i3.Ref);

  @override
  set state(dynamic newState) => super.noSuchMethod(
    Invocation.setter(#state, newState),
    returnValueForMissingStub: null,
  );

  @override
  void build() => super.noSuchMethod(
    Invocation.method(#build, []),
    returnValueForMissingStub: null,
  );

  @override
  double calculateSignalScore({
    required _i5.FeedItemModel? item,
    _i6.UserFeedContext? context,
    DateTime? now,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculateSignalScore, [], {
              #item: item,
              #context: context,
              #now: now,
            }),
            returnValue: 0.0,
          )
          as double);

  @override
  double calculateRecencyScore(DateTime? createdAt, DateTime? now) =>
      (super.noSuchMethod(
            Invocation.method(#calculateRecencyScore, [createdAt, now]),
            returnValue: 0.0,
          )
          as double);

  @override
  double calculateRelevanceScore({
    required _i5.FeedItemModel? item,
    _i6.UserFeedContext? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculateRelevanceScore, [], {
              #item: item,
              #context: context,
            }),
            returnValue: 0.0,
          )
          as double);

  @override
  double calculateEngagementScore(_i5.FeedItemModel? item) =>
      (super.noSuchMethod(
            Invocation.method(#calculateEngagementScore, [item]),
            returnValue: 0.0,
          )
          as double);

  @override
  double calculateDiversityScore({
    required String? sourceType,
    required List<String>? recentlyShownTypes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#calculateDiversityScore, [], {
              #sourceType: sourceType,
              #recentlyShownTypes: recentlyShownTypes,
            }),
            returnValue: 0.0,
          )
          as double);

  @override
  double calculateTrustScore(double? itemTrustScore) =>
      (super.noSuchMethod(
            Invocation.method(#calculateTrustScore, [itemTrustScore]),
            returnValue: 0.0,
          )
          as double);

  @override
  double calculateBoostScore(_i5.FeedItemModel? item) =>
      (super.noSuchMethod(
            Invocation.method(#calculateBoostScore, [item]),
            returnValue: 0.0,
          )
          as double);

  @override
  double calculateFinalScore(
    _i5.FeedItemModel? item, {
    _i6.UserFeedContext? context,
    DateTime? now,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #calculateFinalScore,
              [item],
              {#context: context, #now: now},
            ),
            returnValue: 0.0,
          )
          as double);

  @override
  List<_i5.FeedItemModel> rankItems(
    List<_i5.FeedItemModel>? items, {
    _i6.UserFeedContext? context,
    DateTime? now,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #rankItems,
              [items],
              {#context: context, #now: now},
            ),
            returnValue: <_i5.FeedItemModel>[],
          )
          as List<_i5.FeedItemModel>);

  @override
  void runBuild() => super.noSuchMethod(
    Invocation.method(#runBuild, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.RemoveListener listenSelf(
    void Function(void, void)? listener, {
    void Function(Object, StackTrace)? onError,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listenSelf, [listener], {#onError: onError}),
            returnValue: () {},
          )
          as _i7.RemoveListener);

  @override
  bool updateShouldNotify(dynamic previous, dynamic next) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [previous, next]),
            returnValue: false,
          )
          as bool);
}
